### PR TITLE
Package / pythonise and add option to 

### PR DESCRIPTION
**Pull request by a-slide**
The code hasn't changed much but I refactored the code in a standard python package format.
It can now be easily installed with pip directly from github. 
I added an option to set the behaviour of the converter when provided with a fastq file when a fastq sequence is missing (`--missing_fastq {ignore,skip,error}`).
I also added a few non-implemented options that would be nice to implement in the future.
The readme was updated accordingly.

Unfortunately, I did not have time to fix the test module.
I hope it helps

### CODE REVIEW

**Comment by a-slide** [comment]
The following files have been updated by @AlexanderVi since I forked the package, and have be renamed as follow:
cram2ont.py => ont2cram/converter.py
ont2cram.py => ont2cram/reverse_converter.py

I also fixed the header issue the same way in the new version

**Comment by AlexanderVi** [comment]
> cram2ont.py => ont2cram/converter.py
> ont2cram.py => ont2cram/reverse_converter.py

Adrian, did you use 'git mv' or just deleted those files and created them in another place (ont2cram/) ? It seems the history of changes has been lost ...

**Comment by a-slide** [comment]
I believe I just renamed the files :s . I am sorry if it causes issues

**Comment by a-slide** [comment]
I just fixed the data dir path for the test, using `pkg_resources`

**Comment by AlexanderVi** [comment]
Rebased and merged manually - tagged release v0.0.5 ( + includes fixed tests )

**Pull request closed without merging**
